### ISSUE TITLE
Horarios aparecen desordenados al llamar al comando "/horario"

### ISSUE THREAD

**Issue by nestoroa** [CoreDumped-ETSISI/etsisi-telegram-bot#1]
Por ejemplo:
> Horario de hoy para GT22:
> A las 19:00h -> IA
> A las 17:00h -> BD
> A las 15:00h -> AL

Esto puede ser debido a cómo está estructurado `horarios.json`
¿A alguien se le ocurre cómo solucionarlo?

**Comment by zugazagoitia** [comment]
De dónde te sacas esta "Hora", porque no encuentro el origen. https://github.com/CoreDumped-ETSISI/etsisi-telegram-bot/blob/master/bot.py#L144

**Comment by nestoroa** [comment]
Resuelto en https://github.com/CoreDumped-ETSISI/etsisi-telegram-bot/commit/74a0e8ddd19f8fb3838edff4db579227d340735d gracias a @Yadkee
